(function(){
'use strict';
const CONFIG = window.KHIF_ADMIN_SECRET;
const $ = id => document.getElementById(id);
const DEFAULT_CONFIG = { fontSizes: { kicker: 2.2, title: 7, text: 3, footer: 1.3 } };
let token = null;
let sha = null;
let data = null;
let selectedIndex = 0;
let mediaFiles = [];
let imageSlot = 0;
let lastEmojiTarget = null;

const els = {
  loginPanel: $('loginPanel'), editorPanel: $('editorPanel'), logoutButton: $('logoutButton'),
  username: $('username'), password: $('password'), loginButton: $('loginButton'), loginMessage: $('loginMessage'),
  pageTabs: $('pageTabs'), form: $('editorForm'), saveMessage: $('saveMessage'), previewButton: $('previewButton'), previewAllButton: $('previewAllButton'),
  basisConfigPanel: $('basisConfigPanel'), pageEditorPanel: $('pageEditorPanel'),
  fontKicker: $('fontKicker'), fontTitle: $('fontTitle'), fontText: $('fontText'), fontFooter: $('fontFooter'),
  kickerSizeValue: $('kickerSizeValue'), titleSizeValue: $('titleSizeValue'), textSizeValue: $('textSizeValue'), footerSizeValue: $('footerSizeValue'),
  addPageButton: $('addPageButton'), removePageButton: $('removePageButton'),
  enabled: $('enabled'), kicker: $('kicker'), title: $('title'), text: $('text'), footer: $('footer'),
  backgroundColor: $('backgroundColor'), textColor: $('textColor'), accentColor: $('accentColor'),
  image1: $('image1'), image2: $('image2'), image3: $('image3'), uploadSlot: $('uploadSlot'), imageUpload: $('imageUpload'),
  repoVersion: $('repoVersion'), repoUpdated: $('repoUpdated'), deployedVersion: $('deployedVersion'), deployedChecked: $('deployedChecked'), screenEta: $('screenEta'), deployStatus: $('deployStatus'), checkDeployButton: $('checkDeployButton'),
  mediaLibrary: $('mediaLibrary'), refreshMediaButton: $('refreshMediaButton'), imageModal: $('imageModal'), closeImageModal: $('closeImageModal'), imagePickerGrid: $('imagePickerGrid'),
  emojiButton: $('emojiButton'), emojiModal: $('emojiModal'), closeEmojiModal: $('closeEmojiModal'), emojiSearch: $('emojiSearch'), emojiGrid: $('emojiGrid')
};

function msg(el, text, error=false){ if(!el) return; el.textContent = text || ''; el.classList.toggle('error', !!error); }
function friendlyError(error){ if(error?.name === 'OperationError' || String(error?.message || error || '').includes('OperationError')) return 'Forkert brugernavn eller password.'; return error?.message || String(error || 'Ukendt fejl'); }
function formatDate(v){ if(!v) return '-'; const d = new Date(v); return Number.isNaN(d.getTime()) ? String(v) : d.toLocaleString('da-DK'); }
function formatTime(v){ const d = new Date(v); return Number.isNaN(d.getTime()) ? '-' : d.toLocaleTimeString('da-DK', { hour:'2-digit', minute:'2-digit' }); }
function contentVersion(o){ return o?.meta?.version ?? o?.version ?? 0; }
function ensureMeta(){ data.meta = data.meta || {}; data.meta.version = Number(data.meta.version || 0); return data.meta; }
function ensureConfig(){ data.config = data.config || {}; data.config.fontSizes = { ...DEFAULT_CONFIG.fontSizes, ...(data.config.fontSizes || {}) }; return data.config; }
function b64ToBytes(b64){ return Uint8Array.from(atob(b64), c => c.charCodeAt(0)); }
function utf8ToB64(text){ const bytes = new TextEncoder().encode(text); let bin = ''; bytes.forEach(b => bin += String.fromCharCode(b)); return btoa(bin); }
function b64ToUtf8(b64){ return new TextDecoder().decode(Uint8Array.from(atob(b64), c => c.charCodeAt(0))); }
function normalize(text){ return String(text || '').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,''); }

async function deriveKey(password, salt){ const baseKey = await crypto.subtle.importKey('raw', new TextEncoder().encode(password), 'PBKDF2', false, ['deriveKey']); return crypto.subtle.deriveKey({ name:'PBKDF2', salt, iterations: CONFIG.iterations || 250000, hash:'SHA-256' }, baseKey, { name:'AES-GCM', length:256 }, false, ['decrypt']); }
async function decryptToken(password){ if(!CONFIG) throw new Error('secret.js er ikke indlæst.'); const key = await deriveKey(password, b64ToBytes(CONFIG.salt)); const decrypted = await crypto.subtle.decrypt({ name:'AES-GCM', iv:b64ToBytes(CONFIG.iv) }, key, b64ToBytes(CONFIG.encryptedToken)); return new TextDecoder().decode(decrypted); }
async function githubContent(path, options={}){ const res = await fetch(`https://api.github.com/repos/${CONFIG.owner}/${CONFIG.repo}/contents/${path}`, { ...options, headers:{ Accept:'application/vnd.github+json', Authorization:`Bearer ${token}`, 'X-GitHub-Api-Version':'2022-11-28', ...(options.headers||{}) } }); const json = await res.json().catch(()=>({})); if(!res.ok) throw new Error(json.message || `GitHub API fejl ${res.status}`); return json; }

function defaultPage(n){ return { enabled:true, kicker:'KHIF Info', title:`Ny page ${n}`, text:'', footer:'', backgroundColor:'#111827', textColor:'#f9fafb', accentColor:'#f59e0b', images:[], image:'' }; }
function pageImages(page){ const source = Array.isArray(page.images) && page.images.filter(Boolean).length ? page.images : [page.image]; const out = []; source.forEach(x => { const s = String(x || '').trim(); if(s && !out.includes(s)) out.push(s); }); return out.slice(0,3); }

async function loadPages(){ const file = await githubContent(CONFIG.contentPath); sha = file.sha; data = JSON.parse(b64ToUtf8(String(file.content || '').replace(/\n/g,''))); if(!Array.isArray(data.pages)) data.pages = []; if(!data.pages.length) data.pages.push(defaultPage(1)); selectedIndex = Math.min(Math.max(selectedIndex,0), data.pages.length-1); ensureMeta(); ensureConfig(); await loadMedia(); renderTabs(); fillBasis(); fillForm(); updateRepoStatus(); await checkDeploy(); }
function updateRepoStatus(){ const m = ensureMeta(); if(els.repoVersion) els.repoVersion.textContent = `v${m.version || 0}`; if(els.repoUpdated) els.repoUpdated.textContent = `Gemt: ${formatDate(m.updatedAt)}`; }
function setPill(text, cls='neutral'){ if(!els.deployStatus) return; els.deployStatus.textContent = text; els.deployStatus.className = `status-pill ${cls}`; }
async function checkDeploy(){ try{ setPill('Tjekker…'); const checked = new Date(); const res = await fetch(`../${CONFIG.contentPath}?t=${Date.now()}`, { cache:'no-store' }); if(!res.ok) throw new Error(`HTTP ${res.status}`); const deployed = await res.json(); const dv = Number(contentVersion(deployed)); const rv = Number(contentVersion(data)); if(els.deployedVersion) els.deployedVersion.textContent = `v${dv || 0}`; if(els.deployedChecked) els.deployedChecked.textContent = `Tjekket: ${formatDate(checked)}`; if(dv === rv){ if(els.screenEta) els.screenEta.textContent = `Senest ca. ${formatTime(new Date(checked.getTime()+60000))}`; setPill('Klar på Pages','ok'); } else { if(els.screenEta) els.screenEta.textContent = 'Afventer'; setPill('Opdatering igang','pending'); } } catch(error){ if(els.deployedVersion) els.deployedVersion.textContent = '-'; if(els.deployedChecked) els.deployedChecked.textContent = friendlyError(error); if(els.screenEta) els.screenEta.textContent = '-'; setPill('Kunne ikke tjekke','error'); } }

async function loadMedia(){ try{ const list = await githubContent('assets/uploads'); mediaFiles = (Array.isArray(list)?list:[]).filter(x => x.type === 'file' && /\.(png|jpe?g|gif|webp|svg)$/i.test(x.name)).map(x => ({ name:x.name, path:x.path, sha:x.sha, url:`/khif-info/${x.path}` })); renderMedia(); renderPicker(); } catch(error){ mediaFiles = []; renderMedia(`Kunne ikke læse assets/uploads: ${friendlyError(error)}`); renderPicker(); } }
function renderMedia(error){ if(!els.mediaLibrary) return; if(error){ els.mediaLibrary.innerHTML = `<p class="message error">${error}</p>`; return; } if(!mediaFiles.length){ els.mediaLibrary.innerHTML = '<p class="message">Ingen billeder fundet.</p>'; return; } els.mediaLibrary.innerHTML = mediaFiles.map((m,i)=>`<div class="media-item"><img src="${m.url}?t=${Date.now()}" alt=""><code>${m.name}</code><button type="button" class="danger" data-del="${i}">Slet</button></div>`).join(''); els.mediaLibrary.querySelectorAll('[data-del]').forEach(b => b.onclick = () => deleteImage(Number(b.dataset.del))); }
function renderPicker(){ if(!els.imagePickerGrid) return; if(!mediaFiles.length){ els.imagePickerGrid.innerHTML = '<p class="message">Ingen billeder fundet.</p>'; return; } els.imagePickerGrid.innerHTML = mediaFiles.map((m,i)=>`<div class="media-item"><img src="${m.url}?t=${Date.now()}" alt=""><code>${m.name}</code><button type="button" class="secondary" data-pick="${i}">Vælg</button></div>`).join(''); els.imagePickerGrid.querySelectorAll('[data-pick]').forEach(b => b.onclick = () => { [els.image1,els.image2,els.image3][imageSlot].value = mediaFiles[Number(b.dataset.pick)].url; els.imageModal?.classList.add('hidden'); }); }
async function deleteImage(i){ const file = mediaFiles[i]; if(!file || !confirm(`Slet ${file.name}?`)) return; await githubContent(file.path, { method:'DELETE', body:JSON.stringify({ message:`Delete KHIF Info image ${file.name}`, sha:file.sha, branch:CONFIG.branch }) }); await loadMedia(); }

function renderTabs(){ if(!els.pageTabs) return; els.pageTabs.innerHTML = ''; const basis = document.createElement('button'); basis.type='button'; basis.textContent='Basis Config'; basis.className = selectedIndex === -1 ? 'active' : ''; basis.onclick = () => { saveCurrent(); selectedIndex = -1; renderTabs(); fillBasis(); togglePanels(); }; els.pageTabs.appendChild(basis); data.pages.forEach((p,i)=>{ const b = document.createElement('button'); b.type='button'; b.textContent = `Page ${i+1}: ${p.title || 'Uden titel'}`; b.className = i === selectedIndex ? 'active' : ''; b.onclick = () => { saveCurrent(); selectedIndex = i; renderTabs(); fillForm(); togglePanels(); }; els.pageTabs.appendChild(b); }); togglePanels(); }
function togglePanels(){ const basis = selectedIndex === -1; els.basisConfigPanel?.classList.toggle('hidden', !basis); els.pageEditorPanel?.classList.toggle('hidden', basis); els.previewButton?.classList.toggle('hidden', basis); if(els.removePageButton) els.removePageButton.disabled = basis || data.pages.length <= 1; }
function labels(){ if(els.kickerSizeValue) els.kickerSizeValue.textContent = `${els.fontKicker.value}rem`; if(els.titleSizeValue) els.titleSizeValue.textContent = `${els.fontTitle.value}rem`; if(els.textSizeValue) els.textSizeValue.textContent = `${els.fontText.value}rem`; if(els.footerSizeValue) els.footerSizeValue.textContent = `${els.fontFooter.value}rem`; }
function fillBasis(){ const s = ensureConfig().fontSizes; if(els.fontKicker) els.fontKicker.value = s.kicker; if(els.fontTitle) els.fontTitle.value = s.title; if(els.fontText) els.fontText.value = s.text; if(els.fontFooter) els.fontFooter.value = s.footer; labels(); togglePanels(); }
function saveBasis(){ ensureConfig().fontSizes = { kicker:Number(els.fontKicker?.value || 2.2), title:Number(els.fontTitle?.value || 7), text:Number(els.fontText?.value || 3), footer:Number(els.fontFooter?.value || 1.3) }; }
function fillForm(){ if(selectedIndex < 0) return togglePanels(); const p = data.pages[selectedIndex]; const im = pageImages(p); if(els.enabled) els.enabled.checked = p.enabled !== false; if(els.kicker) els.kicker.value = p.kicker || ''; if(els.title) els.title.value = p.title || ''; if(els.text) els.text.value = p.text || ''; if(els.footer) els.footer.value = p.footer || ''; if(els.backgroundColor) els.backgroundColor.value = p.backgroundColor || '#111827'; if(els.textColor) els.textColor.value = p.textColor || '#f9fafb'; if(els.accentColor) els.accentColor.value = p.accentColor || '#f59e0b'; if(els.image1) els.image1.value = im[0] || ''; if(els.image2) els.image2.value = im[1] || ''; if(els.image3) els.image3.value = im[2] || ''; if(els.imageUpload) els.imageUpload.value = ''; togglePanels(); }
function pageFromForm(){ const images = [els.image1?.value,els.image2?.value,els.image3?.value].filter(Boolean).map(x=>x.trim()).filter(Boolean).slice(0,3); return { enabled:els.enabled?.checked !== false, kicker:els.kicker?.value || '', title:els.title?.value || '', text:els.text?.value || '', footer:els.footer?.value || '', backgroundColor:els.backgroundColor?.value || '#111827', textColor:els.textColor?.value || '#f9fafb', accentColor:els.accentColor?.value || '#f59e0b', image:images[0] || '', images }; }
function saveCurrent(){ if(!data) return; saveBasis(); if(selectedIndex < 0 || !data.pages[selectedIndex]) return; Object.assign(data.pages[selectedIndex], pageFromForm()); }
function fileName(name){ const ext=(name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'').slice(0,8)||'jpg'; const base=name.replace(/\.[^.]+$/,'').toLowerCase().replace(/[^a-z0-9-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,40)||'image'; return `${Date.now()}-${base}.${ext}`; }
async function fileToB64(file){ const buf = await file.arrayBuffer(); const bytes = new Uint8Array(buf); let bin=''; bytes.forEach(b => bin += String.fromCharCode(b)); return btoa(bin); }
async function uploadIfNeeded(){ if(selectedIndex < 0 || !els.imageUpload?.files?.[0]) return; const file = els.imageUpload.files[0]; if(!file.type.startsWith('image/')) throw new Error('Den valgte fil er ikke et billede.'); const name = fileName(file.name); const path = `assets/uploads/${name}`; await githubContent(path, { method:'PUT', body:JSON.stringify({ message:`Upload KHIF Info image ${name}`, content:await fileToB64(file), branch:CONFIG.branch }) }); [els.image1,els.image2,els.image3][Number(els.uploadSlot?.value || 0)].value = `/khif-info/${path}`; }
async function savePages(){ await uploadIfNeeded(); saveCurrent(); const m = ensureMeta(); m.version = Number(m.version || 0) + 1; m.updatedAt = new Date().toISOString(); m.updatedBy = CONFIG.adminUsername || 'admin'; const res = await githubContent(CONFIG.contentPath, { method:'PUT', body:JSON.stringify({ message:`Update KHIF Info content v${m.version}`, content:utf8ToB64(JSON.stringify(data,null,2)+'\n'), sha, branch:CONFIG.branch }) }); sha = res.content.sha; await loadMedia(); renderTabs(); fillBasis(); if(selectedIndex >= 0) fillForm(); updateRepoStatus(); await checkDeploy(); }
async function login(){ try{ msg(els.loginMessage,'Logger ind…'); els.loginButton.disabled = true; if(!CONFIG) throw new Error('Admin-konfiguration mangler i secret.js.'); if((els.username.value || '').trim() !== CONFIG.adminUsername) throw new Error('Forkert brugernavn eller password.'); token = await decryptToken(els.password.value); await loadPages(); els.loginPanel.classList.add('hidden'); els.editorPanel.classList.remove('hidden'); els.logoutButton?.classList.remove('hidden'); els.password.value = ''; msg(els.loginMessage,''); } catch(error){ token = null; msg(els.loginMessage, friendlyError(error), true); } finally { els.loginButton.disabled = false; } }
function addPage(){ saveCurrent(); data.pages.push(defaultPage(data.pages.length+1)); selectedIndex = data.pages.length-1; renderTabs(); fillForm(); }
function removePage(){ if(selectedIndex < 0 || data.pages.length <= 1) return; if(confirm('Fjern page?')){ data.pages.splice(selectedIndex,1); selectedIndex = Math.min(selectedIndex, data.pages.length-1); renderTabs(); fillForm(); } }
function openPreview(all){ saveCurrent(); const payload = all ? { pages:data.pages, config:ensureConfig(), index:Math.max(0, selectedIndex) } : { pages:[pageFromForm()], config:ensureConfig(), index:0 }; sessionStorage.setItem('khif-preview-data', JSON.stringify(payload)); window.open('./preview.html', all ? 'khifPreviewAll' : 'khifPreview', 'width=1280,height=780,resizable=yes,scrollbars=no'); }
function emojiItems(){ return (window.KHIF_EMOJIS || []).map(item => ({ e:item.emoji || item.e, k:Array.isArray(item.keywords) ? item.keywords.join(' ') : String(item.keywords || item.k || '') })).filter(item => item.e); }
function insertAtCursor(el,text){ if(!el) return; const s=el.selectionStart ?? el.value.length; const e=el.selectionEnd ?? el.value.length; el.value = el.value.slice(0,s) + text + el.value.slice(e); el.focus(); el.selectionStart = el.selectionEnd = s + text.length; el.dispatchEvent(new Event('input',{bubbles:true})); }
function renderEmoji(query=''){ if(!els.emojiGrid) return; const q = normalize(query); els.emojiGrid.innerHTML = emojiItems().filter(item => !q || normalize(`${item.e} ${item.k}`).includes(q)).map(item => `<button type="button" title="${item.k}">${item.e}</button>`).join(''); els.emojiGrid.querySelectorAll('button').forEach(b => b.onclick = () => { insertAtCursor(lastEmojiTarget || els.text, b.textContent); els.emojiModal?.classList.add('hidden'); }); }
function init(){ if(!els.loginButton) return; msg(els.loginMessage,'Klar til login.'); els.loginButton.onclick = login; els.password?.addEventListener('keydown', e => { if(e.key === 'Enter') login(); }); [els.fontKicker,els.fontTitle,els.fontText,els.fontFooter].filter(Boolean).forEach(el => el.addEventListener('input', labels)); document.querySelectorAll('.emoji-target').forEach(el => el.addEventListener('focus', () => lastEmojiTarget = el)); if(els.emojiButton) els.emojiButton.onclick = () => { renderEmoji(); els.emojiModal?.classList.remove('hidden'); els.emojiSearch?.focus(); }; if(els.emojiSearch) els.emojiSearch.oninput = () => renderEmoji(els.emojiSearch.value); if(els.closeEmojiModal) els.closeEmojiModal.onclick = () => els.emojiModal?.classList.add('hidden'); [1,2,3].forEach((n,i)=>{ const choose=$(`chooseImage${n}`); const upload=$(`uploadImage${n}`); if(choose) choose.onclick=()=>{ imageSlot=i; renderPicker(); els.imageModal?.classList.remove('hidden'); }; if(upload) upload.onclick=()=>{ imageSlot=i; if(els.uploadSlot) els.uploadSlot.value=String(i); els.imageUpload?.click(); }; }); if(els.closeImageModal) els.closeImageModal.onclick=()=>els.imageModal?.classList.add('hidden'); const clear=$('clearImagesButton'); if(clear) clear.onclick=()=>{ if(els.image1) els.image1.value=''; if(els.image2) els.image2.value=''; if(els.image3) els.image3.value=''; }; if(els.addPageButton) els.addPageButton.onclick=addPage; if(els.removePageButton) els.removePageButton.onclick=removePage; if(els.refreshMediaButton) els.refreshMediaButton.onclick=loadMedia; if(els.form) els.form.onsubmit=async e=>{ e.preventDefault(); try{ msg(els.saveMessage, els.imageUpload?.files?.[0] ? 'Uploader billede og gemmer…' : 'Gemmer…'); await savePages(); msg(els.saveMessage,'Gemt. Brug “Tjek deploy status” for at se hvornår ændringen er ude.'); } catch(error){ msg(els.saveMessage, friendlyError(error), true); } }; if(els.previewButton) els.previewButton.onclick=e=>{e.preventDefault();openPreview(false)}; if(els.previewAllButton) els.previewAllButton.onclick=e=>{e.preventDefault();openPreview(true)}; if(els.logoutButton) els.logoutButton.onclick=()=>location.reload(); if(els.checkDeployButton) els.checkDeployButton.onclick=checkDeploy; }
if(document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init); else init();
})();
